name: CI for Hello World

on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Libraries
      run: |
        pip install flake8 pytest pytest-cov
    - name: Checkout Own Repo
      uses: actions/checkout@v2
      with:
        repository: DevOps-Team4-2022/DevOps_Oct2022_Team4_Week4
    - name: List out contents
      run: |
        ls
