name: CI for Hello World

on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.10.8
    - name: Install Libraries
      run: |
        pip install flake8 pytest pytest-cov 
    - name: Checkout Own Repo
      uses: actions/checkout@v2
      with:
        repository: DevOps-Team4-2022/DevOps_Oct2022_Team4_Week4
    - name: List out contents
      run: |
        ls
    - name: test with pytest
      run: |
        pytest test.py -v -cov --junitxml=report.xml
        
    - if: ${{ failure() }}
      uses: nashmaniac/create-issue-action@v1.1
      name: Create Issue Action
      with:
        title: Build Failed
        token: ${{secrets.GITHUB_TOKEN}}
        assignees: ${{github.actor}}
        labels: worflow-failed
        body: Workflow failed for commit ${{github.sha}}

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v2
      if: always()
      with:
        junit_files: "report.xml"
